/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:19c09f73-d071-40fa-90e1-19506862f6de",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_bvlpfqV93",
    "aws_user_pools_web_client_id": "1q19m0m4jaek78na0oj2vdls2s",
    "oauth": {}
};


export default awsmobile;
